title: Cheatsheet
longtitle: Cheatsheet
author: Sebastian Krüger
email: sk@honeymachine.io
description: >
  Some snippets i collect through debugging.

url: "https://artificialhoney.github.io"
baseurl: "/cheatsheet"

theme: just-the-docs

sass:
  sass_dir: _sass
  style: compressed

# Just The Docs
color_scheme: honeymachine

aux_links:
  "GitHub": "https://github.com/artificialhoney/cheatsheet"

nav_external_links: []

gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/artificialhoney/cheatsheet" # the github URL for your repo

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: ""
